{% set name = "plasticparcels" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oceanparcels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e48d4441a016f803364a515ab273915f710b83be2ed4de0e568d896fdb81aef5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=64
    - setuptools_scm >=8
    - wheel
  run:
    - python >=3.8
    - parcels >=3.0.2
    - shapely
    - geopandas

test:
  imports:
    - plasticparcels
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OceanParcels/plasticparcels
  summary: 'Ready-to-use tool for plastic dispersion simulations and parameterisation development'
  description: |
    plasticparcels is a python package for simulating the transport and dispersion of plastics in the ocean.
    The tool is based on the parcels computational Lagrangian ocean analysis framework,
    providing a modular and customisable collection of methods, notebooks, and tutorials
    for advecting virtual plastic particles with a wide range of physical properties.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://plastic.oceanparcels.org
  dev_url: https://github.com/OceanParcels/plasticparcels

extra:
  recipe-maintainers:
    - erikvansebille
    - michaeldenes
